package-lock.json
package.json
src/Components/Common/Body.tsx

[SCRUM-76/html&css] Contact Us Button 삭제

---

src/Pages/ArtworkPage/ArtworkMainPage.tsx
src/Pages/ContactPage/ContactPage.tsx
src/Pages/ContactPage/ContactPage2.tsx
src/Pages/LoginPage/LoginMainPage.tsx
src/Pages/MainPage/MainAbout.tsx
src/Pages/MainPage/MainContents.tsx
src/Pages/MainPage/MainLogoSlider.tsx
src/Router.tsx
src/setupProxy.tsx

- header contact ContactPage2에서 ContactPage로 변경
- 타입명시 후 create project error 해결

[Hotfix] request post error

---

src/Pages/AdminPage/AboutEditPage.tsx
src/Pages/AdminPage/ArtworkEditPage.tsx
src/Pages/AdminPage/ContactEditPage.tsx
src/Pages/AdminPage/MainEditPage.tsx
src/setupProxy.tsx

[Hotfix] test code 삭제

---

src/Pages/PromotionAdmin/FAQPage/FAQManagePage.tsx

fix: reload error

---

src/Components/PromotionAdmin/Request/RequestList.tsx
src/apis/PromotionAdmin/request.ts
src/pages/PromotionAdmin/RequestPage/index.tsx
src/types/PromotionAdmin/request.ts

[SCRUM-162] feat: request 목록 조회

---

src/Router.tsx
src/apis/PromotionPage/artwork.ts
src/components/PromotionPage/Artwork/Components.tsx
src/components/PromotionPage/Artwork/ImageSlider.tsx
src/components/PromotionPage/Artwork/Navigation.tsx
src/components/PromotionPage/Artwork/RotatedCircle.tsx
src/components/PromotionPage/Artwork/ScrollAnimatedComponent.tsx
src/constants/routerConstants.ts
src/pages/PromotionPage/ArtworkPage/ArtworkDetailPage.tsx
src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
src/types/PromotionPage/artwork.ts

[SCRUM-168] feat: artwork 상세 페이지 조회

---

src/components/PromotionPage/Artwork/ArtworkCard.tsx
src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx

#39 
- artwork is-posted가 ture인 경우에만 공개

fix: artwork is-posted 반영

---

package-lock.json
package.json
src/Router.tsx
src/constants/routerConstants.ts
src/pages/PromotionPage/FaqPage/FaqPage.tsx

#SCRUM-219
일반 사용자는 프로모션 FAQ페이지에서 FAQ 리스트를 조회할 수 있다.
참고해야할 부분 작성
참고해야할 부분 작성

design: pp faq

---

src/pages/PromotionPage/AboutPage/WhatWeDoPage.tsx
src/pages/PromotionPage/ContactPage/ContactUsPage.tsx

#해당이슈번호
참고해야할 부분 작성
참고해야할 부분 작성

PP-ContactPage change

---

src/pages/PromotionPage/AboutPage/WhatWeDoPage.tsx

#해당이슈번호
참고해야할 부분 작성
참고해야할 부분 작성

PP-About-WhatWeDo fix

---

src/apis/PromotionAdmin/faq.ts
src/components/Pagination/Pagination.tsx
src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
src/types/PromotionAdmin/faq.ts

#65 
Pagination 컴포넌트
src>components>Pagination>Pagination.tsx
사용방법(PA Faq 페이지를 예로 들어서 설명)
1) api 불러오기
```typescript
export const getFAQPaginateData = async (page: number, perPage: number) => {
try {
const response = await axios.get(`${PROMOTION_BASIC_PATH}/api/faq/page?page=${page}&size=${perPage}`);
return response.data;
} catch (error) {
console.log('[❌ Error fetching all artworks]', error);
throw error;
}
};
```
2) type 정의하기
```typescript
export interface IContentItem {
id: number;
question: string;
answer: string;
visibility: boolean;
}
export interface IPageable {
pageNumber: number;
pageSize: number;
sort: any[];
offset: number;
paged: boolean;
unpaged: boolean;
}
export interface IPaginationData {
content: IContentItem[];
pageable: IPageable;
totalPages: number;
totalElements: …
```

feat:  Pagination

---

src/pages/PromotionAdmin/RequestPage/RequestCheckPage.tsx
src/pages/PromotionAdmin/RequestPage/RequestManagePage.tsx

#해당이슈번호
참고해야할 부분 작성
참고해야할 부분 작성

[feat] PA RequestPage 관련 이슈 수정

---

src/components/BackgroundYellowCircle/BackgroundYellowCircle.tsx
src/components/PromotionAdmin/DataEdit/Company/StyleComponents.tsx
src/components/PromotionAdmin/DataEdit/TextColorEditor.tsx
src/pages/PromotionAdmin/DataEditPage/CEOPage/CEOEditPage.tsx
src/pages/PromotionAdmin/DataEditPage/CEOPage/CEOPage.tsx
src/pages/PromotionAdmin/DataEditPage/CEOPage/CEOWritePage.tsx
src/pages/PromotionPage/AboutPage/AboutPage.tsx
src/pages/PromotionPage/AboutPage/IntroPage.tsx
src/pages/PromotionPage/ContactPage/ContactUsPage.tsx

#해당이슈번호
참고해야할 부분 작성
참고해야할 부분 작성

final_issue_check02

---

src/components/PromotionAdmin/DataEdit/TextColorEditor.tsx
src/pages/PromotionAdmin/DataEditPage/CEOPage/CEOEditPage.tsx
src/pages/PromotionAdmin/DataEditPage/CEOPage/CEOPage.tsx
src/pages/PromotionAdmin/DataEditPage/CEOPage/CEOWritePage.tsx
src/pages/PromotionPage/AboutPage/AboutPage.tsx
src/pages/PromotionPage/ContactPage/ContactUsPage.tsx
src/pages/PromotionPage/FaqPage/FaqPage.tsx

#해당이슈번호
참고해야할 부분 작성
참고해야할 부분 작성

final_issue_check03

---

src/components/PromotionAdmin/DataEdit/Client/Client.tsx
src/components/PromotionAdmin/DataEdit/Company/CompanyInfo.tsx
src/components/PromotionAdmin/DataEdit/Company/EditForm/Basic.tsx
src/components/PromotionAdmin/DataEdit/Company/EditForm/Detail.tsx
src/components/PromotionAdmin/DataEdit/Company/EditForm/Image.tsx
src/components/PromotionAdmin/DataEdit/Company/EditForm/Introduction.tsx
src/components/PromotionAdmin/DataEdit/Company/InfoCard/Basic.tsx
src/components/PromotionAdmin/DataEdit/Company/InfoCard/Detail.tsx
src/components/PromotionAdmin/DataEdit/Company/InfoCard/Introduction.tsx
src/components/PromotionAdmin/DataEdit/Company/InputForm.tsx
src/components/PromotionAdmin/DataEdit/Partner/Partner.tsx
src/constants/messages.ts

constant > messages.ts에서 메시지 관리

refactor: message 상수 파일 생성 및 Data Edit에 적용

---

src/components/PromotionAdmin/DataEdit/Company/InputForm.tsx
src/pages/PromotionAdmin/DataEditPage/CEOPage/CEOEditPage.tsx
src/pages/PromotionAdmin/DataEditPage/CEOPage/CEOPage.tsx
src/pages/PromotionAdmin/DataEditPage/CEOPage/CEOWritePage.tsx
src/pages/PromotionPage/AboutPage/IntroPage.tsx

#해당이슈번호
참고해야할 부분 작성
참고해야할 부분 작성

PA-CEOPage

---

src/components/PromotionAdmin/DataEdit/Client/Client.tsx
src/components/PromotionAdmin/DataEdit/Company/CompanyInfo.tsx
src/components/PromotionAdmin/DataEdit/Company/EditForm/Basic.tsx
src/components/PromotionAdmin/DataEdit/Company/EditForm/Detail.tsx
src/components/PromotionAdmin/DataEdit/Company/EditForm/Image.tsx
src/components/PromotionAdmin/DataEdit/Company/EditForm/Introduction.tsx
src/components/PromotionAdmin/DataEdit/Company/InputForm.tsx
src/components/PromotionAdmin/DataEdit/Partner/Partner.tsx
src/components/PromotionAdmin/DataEdit/StyleComponents/ToggleSwitch.tsx
src/pages/PromotionAdmin/DataEditPage/ClientPage/ClientEditPage.tsx
src/pages/PromotionAdmin/DataEditPage/ClientPage/ClientWritePage.tsx
src/pages/PromotionAdmin/DataEditPage/PartnerPage/PartnerEditPage.tsx
src/pages/PromotionAdmin/DataEditPage/PartnerPage/PartnerWritePage.tsx

feat: data edit 수정 중 이동 시 경고

---

src/components/PromotionPage/Main/ArtworkNav.tsx
src/pages/PromotionAdmin/RequestPage/RequestCheckPage.tsx

#해당이슈번호
참고해야할 부분 작성
참고해야할 부분 작성

[fix] ArtworkNav 위치 변경, RequestCheckPage 툴팁 문구 변경

---

src/pages/PromotionPage/AboutPage/WhatWeDoPage.tsx

#해당이슈번호
참고해야할 부분 작성
참고해야할 부분 작성

[fix] WhatWeDo api 호출 수정

---

src/pages/PromotionAdmin/RequestPage/RequestCheckPage.tsx
src/pages/PromotionPage/AboutPage/WhatWeDoPage.tsx
src/pages/PromotionPage/ContactPage/ContactUsPage.tsx
src/pages/PromotionPage/FaqPage/FaqDetailPage.tsx
src/pages/PromotionPage/FaqPage/FaqPage.tsx

#해당이슈번호
참고해야할 부분 작성
참고해야할 부분 작성

axios_path_issue

---

src/components/PromotionAdmin/DataEdit/Client/Client.tsx
src/components/PromotionAdmin/DataEdit/Partner/Partner.tsx

Client. Partner 페이지 처음 랜더링 시에 제일 마지막 페이지로 랜더링되는 에러

fix: client, partner pagination error

---

src/index.tsx
src/styles/ReactiveStyle.tsx
src/styles/theme.ts

- 전역 스타일 파일 ReactiveStyle.tsx
- 반응형 기준값 theme.ts에 추가
1. 모든 사이즈는 rem으로 작성할 것.
2. 따로 설정할 것들은 각 컴포넌트의 css에서
```css
const IntroWrapper = styled.div`
font-size: 3rem;
width: 80rem;
max-height: 12rem;
...
@media ${theme.media.tablet}{
color: blue;
}
@media ${theme.media.mobile}{
color: red;
}
`;
```
이런 식으로 !!media!!를 통해 조절해주시면 됩니다.

[SCRUM-260/feat] 반응형 베이스 파일 추가

---

src/components/PromotionPage/Footer/Footer.tsx

[Feat/SCRUM-243-PP] Footer Responsive

---

src/styles/ReactiveStyle.tsx
src/styles/styld.d.ts
src/styles/theme.ts

large tablet 폰트 사이즈 90%
tablet 폰트 사이즈 80%
mobile 폰트 사이즈 70%
small mobile 폰트 사이즈 60%
...이슈 따로 없음

[Fix/SCRUM-260-PP] 반응형 사이즈 세분화

---

src/components/PromotionAdmin/Home/Graph/Graph.tsx
src/components/PromotionAdmin/Home/Graph/LineGraph.tsx
src/components/PromotionAdmin/Home/Graph/PeriodPicker.tsx
src/components/PromotionPage/Layout/Layout.tsx
src/constants/categories.ts
src/hooks/useGraphData.tsx
src/pages/PromotionPage/NewsPage/IntroSection.tsx
src/pages/PromotionPage/NewsPage/NewsBoardPage.tsx
src/pages/PromotionPage/NewsPage/NewsSection.tsx

close #113 
사실 이 번호는 아닌데 저거 닫긴 해야해서... 해당 이슈 만들기는 다음 스크럼부터 할게요...

[Fix/SCRUM-266-PP] PP News 반응형 이슈 수정

---

src/components/PromotionPage/Footer/Footer.tsx

[Fix/ISSUE-PP]  Footer Responsive 모바일 화면 수정

---

src/pages/PromotionPage/FaqPage/FaqPage.tsx

- 창이 깨짐
- X축 오버플로우 막아야할 것 같음
- 검색 바 중앙정렬
- Frequently Asked Questions 줄 늘어날 때 간격 늘리기
- 자주 묻는 질문 문구 단어로 묶어서 안 잘리게(word-break:keep-all), 폰트 적용
- FAQ 선 추가, 배경 쌩으로 검정인 거 수정
close #해당이슈번호

[Feat/SCRUM-264-PP] FAQ Responsive 수정

---

cypress/e2e/faqPage.cy.ts
package-lock.json
package.json
src/components/PromotionPage/Header/Menubar.tsx
src/pages/PromotionPage/FaqPage/FaqPage.tsx
src/pages/PromotionPage/RecruitmentPage/RecruitmentPage.tsx

FAQ 페이지 e2e test 코드 작성
채용공고 페이지 css 수정
아직 빨간불이 많이 떠서 더 수정하겠습니다.. 
close #해당이슈번호

[Feat/SCRUM-282-PP] FAQ Page e2e

---

cypress/e2e/AboutPage.cy.ts
src/pages/PromotionPage/AboutPage/AboutPage.tsx
src/pages/PromotionPage/AboutPage/IntroPage.tsx
src/pages/PromotionPage/AboutPage/WhatWeDoPage.tsx

- Cypress 테스트에서 Main section(WHAT, WE, DO)이 올바르게 렌더링되는지 확인했습니다.
- data-cy 속성(init-title-what, init-title-we, init-title-do)을 이용하여 각 요소의 존재 여부와 가시성을 테스트했습니다.
- About, Mission, WhatWeDo, CEO, Company 섹션이 정상적으로 렌더링되는지 확인하는 테스트 케이스를 작성하였습니다.
- 각 섹션의 주요 텍스트, 이미지가 DOM에 존재하는지, 가시성을 유지하는지 검증했습니다.
- 데이터가 없을 때 올바르게 안내 텍스트가 렌더링되는지 추가로 확인하여 빈 데이터 처리 상태도 검증했습니다.
- What We Do Section에서 사용되는 스크롤 바(scrollbar 및 scrollbar-box 데이터 속성)가 정상적으로 표시되는지 확인하는 추가 테스트를 작성하였습니다.
close #167

[Feat/SCRUM-283-PP] about page e2e

---

cypress/e2e/faqPage.cy.ts
src/pages/PromotionPage/FaqPage/FaqPage.tsx

- FAQ 페이지 E2E 테스트
Cypress 테스트를 통해 FAQ 페이지의 여러 기능을 확인하였습니다.
FAQ 헤더 렌더링 검증
FAQ 질문 검색 기능 검증
FAQ 질문 클릭 기능 검증
모든 질문 확장 가능성 검증
close #해당이슈번호

[Feat/SCRUM-282-PP] FAQ page e2e 수정

---

cypress/e2e/MainPage.cy.ts

[Feat/SCRUM-295-PP] main page e2e 코드 수정

---

src/components/PromotionPage/Client/ClientRowAnimation.tsx
src/components/PromotionPage/Main/ArtworkList.tsx
src/components/PromotionPage/WorkWithUs/WorkWithUs.tsx
src/pages/PromotionPage/Main/MainPage.tsx

[Feat/SCRUM-265] Main Page UI 수정

---

src/components/PromotionPage/Layout/Layout.tsx
src/components/PromotionPage/Main/ArtworkList.tsx
src/pages/PromotionPage/Main/MainPage.tsx

[Feat/PP] 코드 배포2

---

src/pages/PromotionPage/Main/MainPage.tsx

[fix] 푸터 삭제

---

src/apis/PromotionAdmin/dataEdit.ts
src/apis/PromotionPage/company.ts
src/components/PromotionAdmin/DataEdit/Company/CompanyFormStyleComponents.tsx
src/components/PromotionAdmin/DataEdit/Company/EditForm/Image.tsx
src/components/PromotionAdmin/DataEdit/Company/InfoCard/Image.tsx
src/components/PromotionAdmin/DataEdit/Company/InputForm.tsx
src/components/PromotionPage/Footer/Footer.tsx
src/components/PromotionPage/Header/Header.tsx
src/types/PromotionAdmin/dataEdit.ts

추후 PA 페이지 디자인 변경 시 대폭 수정 예정
close #196

[Feat/SCRUM-289] dark/light logo

---

cypress/e2e/Integration/LoginPage.cy.ts
src/components/PromotionPage/Login/Login.tsx

- API 요청에 대해 다양한 시나리오를 모킹(mocking) 처리하여 테스트 환경 구축
- 성공적인 로그인, 잘못된 이메일 형식, 비밀번호 누락 등의 케이스를 테스트
- 잘못된 이메일 형식을 입력했을 때 적절한 오류 메시지가 반환되는지 확인
- 이메일 또는 비밀번호가 비어있을 경우 버튼 비활성화 확인
- 비밀번호 입력 필드가 누락된 경우 요청을 거부하고 버튼 비활성화 처리 확인
-  정상 로그인 시 리디렉션 URL 확인
현재 로그인 계정이 `master` 로 아이디가 설정되어 있는데 다른 테스트가 다 `master`로 진행하여 이메일 유효성 검사를 추후 다시 진행해야 합니다. 
closes #207

[Test/SCRUM-313] Login Page Integration test

---

src/components/PromotionPage/Login/Login.tsx

hotfix: 로그인 이메일 유효성 검사 해제

---

src/apis/PromotionAdmin/request.ts
src/components/PromotionAdmin/Header/index.tsx
src/pages/PromotionAdmin/RequestPage/RequestManagePage.tsx

[Feat/SCRUM-323] PA 문의 삭제

---

cypress/support/hooks.ts
package.json
src/apis/PromotionAdmin/login.ts
src/components/PromotionPage/Login/Login.tsx
src/constants/basicPathConstants.ts

Chore: gateway 주소 삭제 및 기본 주소 통합, 로그인 이메일 유효성 검사 추가

---

package.json
src/Router.tsx
src/components/Loading/Loading.tsx
src/components/PromotionPage/Layout/Loading.tsx
src/loaders/aboutPageLoader.ts
src/pages/ErrorPage/ErrorPage.tsx
src/pages/PromotionPage/AboutPage/AboutPage.tsx
src/pages/PromotionPage/AboutPage/IntroPage.tsx
src/pages/PromotionPage/AboutPage/WhatWeDoPage.tsx
src/types/PromotionPage/about.ts
src/utils/withSuspense.tsx

- `withSuspense.ts`  컴포넌트를 만들어 Router 내 Suspense 코드를 간단하게 정리하고 재활용 가능하도록 개선 
- 타입 정리
- About 페이지에서 사용되는 데이터 타입을 따로 정리
- Loader 적용
- About 페이지와 하위 컴포넌트(Intro, WhatWeDo)에 Loader를 적용해 데이터를 렌더링 전에 미리 로드 
- WhatWeDo와 Intro에서 따로 데이터를 불러오던 방식을 About 페이지의 Loader로 통합 
- Loader 적용 후 데이터 변경 시 바로 반영되지 않는 문제를 해결하기 위해 JSON 복사를 활용해 데이터를 강제로 갱신하도록 조정
- 데이터 로드 실패 또는 기타 예외 상황 발생 시 렌더링될 에러 페이지를 추가해 사용자 경험을 개선 
- Loader를 적용한 이유 
데이터 로드 중에 페이지가 멈추는 문제를 해결하고 사용자 경험을 개선하기 위해 Loader를 적용했습니다.
React Router에서 lazy loading을 사용하면 데이터 로드 동안 로딩 페이지가 **반복적으로** 나타납니다. 
이 때 Loader를 활용하면 페이지 렌더링 전에 데이터를 미리 가져올 수 있어 성능 최적화가 가능합니다.
다만 Loader를 사용한 후 데이터 변경 사항이 반영되지 않는 문제가 있었는데 JSON 복사를 사용해 데이터를 강제로 갱신하도록 조정했습니다.
JSON 복사를 통해 Loader가 반환하는 데이터가 항상 새로운 객체로 전달되어 React가 변경 사항을 제대로 감지하도록 만들었습니다.

[Refactor/SCRUM-318] About Page Performance 개선 

---

src/components/PromotionPage/Main/ArtworkList.tsx
src/components/PromotionPage/Main/ArtworkSlider.tsx
src/components/ValidationRegEx/ValidationRegEx.tsx
src/pages/PromotionAdmin/FaqPage/FAQManagePage.tsx
src/pages/PromotionPage/Main/MainPage.tsx
src/pages/PromotionPage/NewsPage/IntroSection.tsx
src/pages/PromotionPage/NewsPage/NewsBoardPage.tsx
src/pages/PromotionPage/NewsPage/NewsSection.tsx
src/types/PromotionPage/artwork.ts

- 메인 페이지 푸터: 다른 분들 모바일 환경에서도 오류 없는지 확인해야 함
close #226

[Fix/SCRUM-335] Main, News, FAQ 관리, News 관리 페이지 Issue Handling

---

cypress/e2e/Integration/MainPage.cy.ts
src/apis/PromotionPage/artwork.ts
src/components/PromotionAdmin/DataEdit/Company/InfoCard/Introduction.tsx
src/components/PromotionPage/Main/ArtworkList.tsx
src/components/PromotionPage/Main/ArtworkSlider.tsx
src/components/PromotionPage/Main/Intro.tsx
src/components/PromotionPage/Main/Outro.tsx
src/pages/PromotionPage/Main/MainPage.tsx

- Status Code 200: PA에서 데이터가 존재할 경우
기타 섹션에 대한 필수 예외 코드 추가를 이슈 처리해야 합니다.
close #213

[Test/SCRUM-312] Main Page Integration test - Add Exception Code

---

cypress/e2e/Integration/AboutPage.cy.ts
cypress/e2e/System/RecruitmentPage.cy.ts
src/apis/PromotionAdmin/dataEdit.ts

[Test/206-AboutPage-Integration-final]

---

src/pages/PromotionPage/AboutPage/AboutPage.tsx

Data Edit Partner fix

---

src/apis/PromotionAdmin/menu.ts
src/apis/PromotionAdmin/request.ts
src/components/PromotionPage/Header/HeaderDetail.tsx
src/pages/PromotionAdmin/DataEditPage/MenuPage/MenuPage.tsx
src/pages/PromotionAdmin/RequestPage/RequestCheckPage.tsx
src/pages/PromotionAdmin/RequestPage/RequestManagePage.tsx
src/pages/PromotionPage/NewsPage/NewsBoardPage.tsx
src/pages/PromotionPage/NewsPage/NewsSection.tsx

_- 현재 메뉴 api 관련하여 백엔드 분과 컨택 중에 있습니다! 12/5(목) 오후 중으로 메뉴 기능 구현 완료하겠습니다._ 완료

[Fix] PA Request Page, PP News Page, PA Menu Edit 이슈 해결

---

src/components/PromotionAdmin/Recruitment/index.tsx
src/pages/PromotionAdmin/FaqPage/FAQManagePage.tsx
src/pages/PromotionAdmin/RecruitmentPage/BenefitManagePage.tsx
src/pages/PromotionAdmin/RecruitmentPage/BenefitWritePage.tsx
src/pages/PromotionAdmin/RecruitmentPage/RecruitmentManagePage.tsx
src/pages/PromotionAdmin/RecruitmentPage/RecruitmentWritePage.tsx
src/pages/PromotionPage/FaqPage/FaqPage.tsx
src/pages/PromotionPage/RecruitmentPage/RecruitmentPage.tsx

[Fix] PA Recruitment 관리 페이지, PP FAQ 페이지, Recruitment 페이지 이슈 처리

---

cypress/e2e/Integration/LoginPage.cy.ts
cypress/e2e/System/AboutPage/Introduction.cy.ts
cypress/e2e/System/AboutPage/Slogan.cy.ts
cypress/e2e/System/AboutPage/WhatWeDo.cy.ts
cypress/support/hooks.ts
src/components/PromotionAdmin/Home/Graph/Graph.tsx
src/components/PromotionAdmin/Home/Graph/LineGraph.tsx
src/components/PromotionAdmin/Home/RequestSummary/RequestSummary.tsx
src/components/PromotionAdmin/Home/RequestSummary/WaitingRequestsList.tsx
src/hooks/useGraphData.tsx

- Slogan 관련 모킹 제거 및 실제 데이터 기반 테스트 작성
- WhatWeDo 관련 모킹 제거 및 예외 처리 추가
- Introduction 관련 모킹 제거
E2E 테스트에서 예외 처리가 필요한 상황을 모두 다루기 어려운 환경이 있었습니다.
현재 개발된 범위 내에서 예외를 테스트해야 하는 제한이 있었으며, 이러한 점을 참고 부탁드립니다.
closes #174

[Test/SCRUM-174] about page partner e2e test 및 이슈 해결

---

src/components/PromotionPage/Main/Intro.tsx

hotfix: Main Page-Intro 섹션 오류 수정

---

cypress/e2e/System/ArtworkPage.cy.ts
src/components/PromotionAdmin/Artwork/ArtworkDefault/Artwork.tsx

진짜 마지막이길 바라는데 테스트가 되다말다 하는 경향이 좀 있는듯해요
close #161

[Test/SCRUM-161] Artwork test 수정

---

src/components/Pagination/NewsPagination.tsx
src/components/PromotionAdmin/News/NewsList.tsx
src/pages/PromotionAdmin/NewsPage/NewsViewPage/NewsEditPage.tsx
src/pages/PromotionAdmin/NewsPage/NewsViewPage/NewsViewPage.tsx
src/pages/PromotionAdmin/NewsPage/index.tsx
src/pages/PromotionPage/NewsPage/NewsBoardPage.tsx
src/pages/PromotionPage/NewsPage/NewsSection.tsx

hotfix: PP News Page 페이지네이션 스크롤 이슈 해결

---

src/components/PromotionAdmin/Home/RequestSummary/RequestSummary.tsx

fix: PA 홈 페이지 문의 통계 단어 수정
